apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multi-k8s-dulcedosystems-com-tls
spec:
  secretName: multi-k8s-dulcedosystems-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.dulcedosystems.com
  dnsNames:
    - multi-k8s.dulcedosystems.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.dulcedosystems.com
